### ISSUE TITLE
Infografía - Gestion de Proyectos

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-FedericoVictorianoSierra#2]
[INFOGRAFÍA (FEDERICO VICTORIANO SIERRA).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-FedericoVictorianoSierra/files/12457839/INFOGRAFIA.FEDERICO.VICTORIANO.SIERRA.pdf)

**Comment by bg55-a** [comment]
calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
